version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: go-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassabcbxghgwmmrmemrmdhdh
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy  # Wait for the db service to be healthy

    environment:
      DSN: "host=db user=postgres password=mypassabcbxghgwmmrmemrmdhdh dbname=go-db port=5432 sslmode=disable TimeZone=Asia/Ho_Chi_Minh"