// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/booking/": {
            "post": {
                "description": "create a booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "create a booking",
                "parameters": [
                    {
                        "description": "Booking information",
                        "name": "booking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/create_booking.CreateBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/booking.Dto"
                        }
                    }
                }
            }
        },
        "/booking/:bookingId": {
            "get": {
                "description": "Get booking by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Get booking by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Booking ID",
                        "name": "bookingId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/booking.Dto"
                        }
                    }
                }
            }
        },
        "/booking/:hotelId": {
            "get": {
                "description": "Get all bookings",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Get all bookings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/booking.Dto"
                        }
                    }
                }
            }
        },
        "/booking/available": {
            "post": {
                "description": "Get available room",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "booking"
                ],
                "summary": "Get available room",
                "parameters": [
                    {
                        "description": "Filter information",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/booking.AvailableFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/hotels/": {
            "get": {
                "description": "Get all hotels",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotels"
                ],
                "summary": "Get all hotels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel.Hotel"
                            }
                        }
                    }
                }
            }
        },
        "/hotels/{hotelId}/rooms": {
            "get": {
                "description": "Get room by hotel id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotels"
                ],
                "summary": "Get room by hotel id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hotel ID",
                        "name": "hotelId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/hotel.Room"
                            }
                        }
                    }
                }
            }
        },
        "/hotels/{id}": {
            "get": {
                "description": "Get hotel by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "hotels"
                ],
                "summary": "Get hotel by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Hotel ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/hotel.Hotel"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "booking.AvailableFilter": {
            "type": "object",
            "properties": {
                "checkInDate": {
                    "type": "string"
                },
                "checkOutDate": {
                    "type": "string"
                },
                "hotelID": {
                    "type": "string"
                }
            }
        },
        "booking.BookingStatus": {
            "type": "string",
            "enum": [
                "init",
                "process_payment",
                "success_payment",
                "cancel",
                "pending_payment"
            ],
            "x-enum-varnames": [
                "StatusInit",
                "StatusProcessPayment",
                "StatusSuccessPayment",
                "StatusCancel",
                "StatusPendingPayment"
            ]
        },
        "booking.Dto": {
            "type": "object",
            "properties": {
                "checkInDate": {
                    "type": "string"
                },
                "checkOutDate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "hotelID": {
                    "type": "string"
                },
                "id": {
                    "description": "rule base = hotelID checkInDate + checkOutDate + roomID for idempotent",
                    "type": "string"
                },
                "roomId": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/booking.BookingStatus"
                }
            }
        },
        "create_booking.CreateBookingRequest": {
            "type": "object",
            "properties": {
                "checkInDate": {
                    "type": "string"
                },
                "checkOutDate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "hotelID": {
                    "type": "string"
                },
                "roomTypeId": {
                    "type": "integer"
                }
            }
        },
        "hotel.Hotel": {
            "type": "object",
            "properties": {
                "createDate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updateDate": {
                    "type": "string"
                }
            }
        },
        "hotel.Room": {
            "type": "object",
            "properties": {
                "createDate": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "hotelID": {
                    "description": "Composite key part 1",
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "roomID": {
                    "description": "Composite key part 2",
                    "type": "integer"
                },
                "roomType": {
                    "type": "integer"
                },
                "updateDate": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Payment API",
	Description:      "This is payment API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
